### ISSUE TITLE
Dynamic Sites reusable app

### ISSUE THREAD

**Issue by nanuxbe** [kezabelle/django-allowedsites#1]
Hello,

with the release of Django 1.8, I will be releasing in a few days a replacement app from Django DynamicSites (https://bitbucket.org/uysrc/django-dynamicsites).
This will be a 1.8+ only application which will be using django 1.7 and 1.8 features.

As part of that application, I would like to include a modified version of your code (basically all of your code + ability to use aliases for the domain names in the Site model).

I will of course give you credits for this code.
But since it is not available on pypi, I will have to copy it to my repository (for several reasons, I cannot have my package depend on a GH repository instead of a pypi package).
Another solution, if you'd like me to do so, would be for me to create a pypi package for this code but before writing the pull request I wanted to make sure you'd be interested in merging it to this repository.

Cheers :-)

**Comment by kezabelle** [comment]
Hi,
I've never published it to PyPI because, like most of my projects, it was just me tinkering to see what could be done. As such, I've never had it run in production, so I have no idea in what ways it might blow up that I've not seen :)

As for taking the code, I've licensed it under a permissive one so that it could be used. As far as I'm concerned, you're welcome to copy it, or publish it to PyPI, or anything really. I don't really know how the license the module is under (BSD IIRC) gels with whatever you've got, but I'll leave that for you to figure out ;)

If you go the route of copying/vendoring it into another project, having a credit would be nice, and a link back to where the original work came from [ie: this repo] would be ideal, from a historical perspective.

If you prefer to publish it to PyPI (notionally on my behalf, I suppose) so that you can make it a real dependency on your package, I'm not above giving you the commit bit on this repository to continue the work, given the alternative is probably just me leaving it to languish until such time as I personally need it.

Whatever you decide, thank you for graciously taking the time to seek my conversation on the matter.

**Comment by nanuxbe** [comment]
Hi,

well, for now I have copied the code (here: https://bitbucket.org/levit_scs/django-polla/src/default/polla/utils.py#cl-44 ) as it was the easiest way to add the SiteAlias feature and "fix" my dependency problem at the same time.
Now as I guess not everyone has the need for the app I am writing I would think publishing yours on PyPI would be the ideal solution yes. I have to go for today but we can talk more about it in the next few days if you're available.

Even though I haven't made the repository private I haven't communicated anything yet about it, I still have a few things to do until I reach my "publishing milestone", including switching to BSD license instead of MIT and writing the doc.

And you are very welcome, I try to treat others the way I would like to be treated, so taking the time to talk to you about the app was the least I could do ;-)
